package com.chessin.model.playing;

public enum GameResults {
    THREE_FOLD, MATE, DRAW_50_MOVE_RULE, INSUFFICIENT_MATERIAL, STALEMATE, NONE,
    BLACK_RESIGN, WHITE_RESIGN, BLACK_TIMEOUT, WHITE_TIMEOUT, DRAW_AGREEMENT
}
